#version: '3.8'
#
#services:
#  postgres:
#    image: postgres:13.3
#    environment:
#      POSTGRES_DB: "postgresTEST"
#      POSTGRES_USER: "postgres"
#      POSTGRES_PASSWORD: "admin"
#      PGDATA: "/var/lib/postgresql/data/pgdata"
#    volumes:
#      - ../2. Init Database:/docker-entrypoint-initdb.d
#      - .:/var/lib/postgresql/data
#    ports:
#      - "5432:5432"

version: '3.8'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  Gateway:
    image: gateway
    environment:
      DEAL_HOSTNAME: Deal:8081
      APPLICATION_HOSTNAME: Application:8082
    ports:
      - "8085:8085"
    depends_on:
      - Application
      - Deal
    restart: always

  Application:
    image: application
    environment:
      DEAL_HOSTNAME: Deal:8081
    ports:
      - "8082:8082"
    depends_on:
      - Deal
    restart: always

  Deal:
    image: deal
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/Neoflex
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      CONVEYOR_HOSTNAME: Conveyor:8080
    #      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:29092
    ports:
      - "8081:8081"
    depends_on:
      - db
      - Conveyor
      - Dossier
      - kafka
    restart: always

  Conveyor:
    image: conveyor
    ports:
      - "8080:8080"
    restart: always

  Dossier:
    image: dossier
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      SERVICES_DEAL_URL: Deal:8081
    ports:
      - "8083:8083"
    depends_on:
      - kafka
    restart: always

  db:
    image: postgres
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=Neoflex
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    restart: always




  #    restart: always
  #    build:
  #      context: ./
  #      dockerfile: Dockerfile





  # zookeeper:
#  #   image: wurstmeister/zookeeper
#  #   expose:
#  #     - 2181
#  # kafka:
#  #   image: wurstmeister/kafka
#  #   expose:
#  #     - 9092
#  #   ports:
#  #     - "9092:9092"
#  #   depends_on:
#  #     - zookeeper
#  #   environment:
#  #     KAFKA_ADVERTISED_HOST_NAME: localhost
#  #     KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
#
#
#
#  #  zookeeper:
#  #    image: 'bitnami/zookeeper:latest'
#  #    ports:
#  #      - '2181:2181'
#  #    environment:
#  #      - ALLOW_ANONYMOUS_LOGIN=yes
#  #  kafka:
#  #    image: 'bitnami/kafka:latest'
#  #    ports:
#  #      - '9092:9092'
#  #    environment:
#  #      - KAFKA_BROKER_ID=1
#  #      - KAFKA_LISTENERS=PLAINTEXT://:9092
#  #      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
#  #      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
#  #      - ALLOW_PLAINTEXT_LISTENER=yes
#  #    depends_on:
#  #      - zookeeper
#
#
#  #  zookeeper:
#  #    image: wurstmeister/zookeeper
#  #    expose:
#  #      - '2181:2181'
#  #    restart: always
#  #
#  #  kafka:
#  #    image: wurstmeister/kafka
#  #    #    expose:
#  #    #      - 9092
#  #    ports:
#  #      - '9092:9092'
#  #    environment:
#  #      - KAFKA_BROKER_ID=1
#  #      - KAFKA_LISTENERS=PLAINTEXT://:9092
#  #      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
#  #      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
#  #      - ALLOW_PLAINTEXT_LISTENER=yes
#  #    depends_on:
#  #      - zookeeper
#  #    restart: always
#
#  #kafka:
#  #  image: wurstmeister/kafka
#  #  #    expose:
#  #  #      - 9092
#  #  ports:
#  #    - "9093:9093"
#  #  depends_on:
#  #    - zookeeper
#  #  environment:
#  #    KAFKA_ADVERTISED_HOST_NAME: localhost
#  #    KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
#  #  restart: always